
version: '3'
volumes:
 prometheus_data:
 grafana_data:

services:
  # ... other services defined here ...
  prometheus:
    image: prom/prometheus:v2.20.0
    build: 
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: prometheus
    volumes:
      - /Users/rjain/sw/liveproj/anomaly/manning-anomaly/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
     - "4002:80"
     
    environment:
      - PORT=80
      - NODE_ENV=development
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    restart: "unless-stopped"
    expose:
     - "9090"

  grafana:
    image: grafana/grafana:7.1.1
    container_name: grafana
    volumes:
      - /Users/rjain/sw/liveproj/anomaly/manning-anomaly/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - PORT=80
      - NODE_ENV=development
      
    restart: "unless-stopped"
    expose:
     - "3000"


  caddy:
    image: stefanprodan/caddy
    container_name: caddy 
    restart: "unless-stopped"   
    volumes:
      - /Users/rjain/sw/liveproj/anomaly/manning-anomaly/monitoring/caddy:/etc/caddy
    ports:
      - "3000:3000"
      - "9090:9090"
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      
      
 
 