apiVersion: 1

deleteDatasources:
  - name: gdev-influxdb
  - name: gdev-influxdb-telegraf
  - name: gdev-influxdb2
  - name: gdev-influxdb2-influxql
  - name: gdev-loki-0.3
  - name: gdev-loki-0.4

datasources:
 - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
     
  - name: gdev-graphite
    type: graphite
    access: proxy
    url: http://localhost:8180
    jsonData:
      graphiteVersion: "1.1"